### PR TITLE
Week 3 bash shell scripting

### PR DESCRIPTION
**Pull request by bilaldjedovic**
**Pull request for the task:**

- [ ] https://github.com/orgs/allops-solutions/projects/1?pane=issue&itemId=21942435

**Note:** _I uploaded images through wetransfer.com because there was an issue with the GitHub image uploader._

**Chapter 13:** 

https://we.tl/t-skEcKwS58h

**Chapter 14:**

https://we.tl/t-TS7ZGksXHQ

**Chapter 15:**

https://we.tl/t-BC1VPPo6LQ

**Chapter 16:**

https://we.tl/t-Kgxx2ijN40

### CODE REVIEW

**Review by borisbradic — CHANGES_REQUESTED** [review]
Please, remove files from directories which we don't need, for example ".out" etc.. 

I can't see the screenshots, please try to upload them again to GitHub.

**Comment by bilaldjedovic** [comment]
I have made the requested changes based on the pull request
@borisbradic 

And I'm adding pictures into comment.

**Chapter 13:**

Screenshot_2
Screenshot_3
Screenshot_4
Screenshot_5
Screenshot_6
Screenshot_7
Screenshot_8
Screenshot_9
Screenshot_10
Screenshot_11
Screenshot_12
Screenshot_13
Screenshot_14
Screenshot_15
Screenshot_16
Screenshot_17
Screenshot_18
Screenshot_19
Screenshot_20
Screenshot_21
Screenshot_22
Screenshot_23
Screenshot_24
Screenshot_25
Screenshot_26
Screenshot_27
Screenshot_28
Screenshot_29
Screenshot_1

**Chapter 14:**

Screenshot_1
Screenshot_2
Screenshot_3
Screenshot_4
Screenshot_5
Screenshot_6
Screenshot_7
Screenshot_8
Screenshot_9
Screenshot_10
Screenshot_11
Screenshot_12
Screenshot_13
Screenshot_14
Screenshot_15
Screenshot_16
Screenshot_17
Screenshot_18
Screenshot_19
Screenshot_20
Screenshot_21
Screenshot_22
Screenshot_23
Screenshot_24
Screenshot_25
Screenshot_26
Screenshot_27
Screenshot_28
Screenshot_30


**Chapter 15:**

Screenshot_1
Screenshot_2
Screenshot_3
Screenshot_4
Screenshot_5
Screenshot_6
Screenshot_7
Screenshot_8
Screenshot_9
Screenshot_10
Screenshot_11
Screenshot_12
Screenshot_13
Screenshot_14
Screenshot_15
Screenshot_16
Screenshot_17


**Chapter 16:**

Screenshot_1
Screenshot_2
Screenshot_3
Screenshot_4
Screenshot_5
Screenshot_6
Screenshot_7
Screenshot_8
Screenshot_9
Screenshot_18

**Review by borisbradic — CHANGES_REQUESTED** [review]
Screenshots look good, but please 'clean' your directories and leave only bash scripts.

**Comment by bilaldjedovic** [comment]
Can you explain more what you mean under the clean directories? You mean to just leave files with extension ".sh" or?
@borisbradic

**Comment by sqlheisenberg** [comment]
@bilaldjedovic - Boris was probably referencing the `index.html` and other files but i can see you removed them as part of the latest commit
https://github.com/bilaldjedovic/bilal-djedovic-devops-mentorship/pull/4/commits/d89496ed9df8f689a87c326bf150ff2b21619350
This looks good to. 
Let's wait on @borisbradic to double-check since he started reviewing this PR already.

**Review by borisbradic — APPROVED** [review]
We can leave .csv and .sql files as they are part of the script. Approved and merged.

**Pull request merged**
